name: PropiedadesVR
favicon: null
layout_spectrum: 0.9670071797445416
typography_spectrum: 0.1199007099494338
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9886405759025365
  lightness: 0.30965260649099946
  saturation: 0.44809299567714334
  rhythmicContrast: 0.02759118820540607
purpose: []
